"""empty message

Revision ID: 29b341950ba0
Revises: 
Create Date: 2023-08-24 11:54:29.514897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b341950ba0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('skill', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('skill')
    )
    op.create_table('users',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('oauth_token', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('user_profile',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('profile_name', sa.String(), nullable=False),
    sa.Column('experience', sa.Float(), nullable=False),
    sa.Column('gender', sa.String(length=6), nullable=True),
    sa.Column('profile_details', sa.Text(), nullable=True),
    sa.Column('is_external', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('education',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('user_profile_id', sa.String(), nullable=True),
    sa.Column('education_degree', sa.String(), nullable=False),
    sa.Column('university_name', sa.String(), nullable=False),
    sa.Column('grade_cum_percentage', sa.String(), nullable=False),
    sa.Column('passout_year', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('experience',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('user_profile_id', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('organization_name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('projects',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('user_profile_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('roles_and_resp', sa.Text(), nullable=True),
    sa.Column('project_tech', sa.String(), nullable=False),
    sa.Column('tech_worked_on', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('user_skills',
    sa.Column('user_profile_id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_profile_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_skills')
    op.drop_table('projects')
    op.drop_table('experience')
    op.drop_table('education')
    op.drop_table('user_profile')
    op.drop_table('users')
    op.drop_table('skills')
    # ### end Alembic commands ###
