"""empty message

Revision ID: 542e1ca56b52
Revises: f1aac4333d08
Create Date: 2023-10-04 14:59:56.535627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542e1ca56b52'
down_revision = 'f1aac4333d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
