"""empty message

Revision ID: e48921367fdb
Revises: 7c7806750e74
Create Date: 2023-10-04 15:10:23.144805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e48921367fdb'
down_revision = '7c7806750e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.drop_constraint('education_user_profile_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_profile', ['user_profile_id'], ['uuid'], ondelete='CASCADE')

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.drop_constraint('experience_user_profile_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_profile', ['user_profile_id'], ['uuid'], ondelete='CASCADE')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('projects_user_profile_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_profile', ['user_profile_id'], ['uuid'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('projects_user_profile_id_fkey', 'user_profile', ['user_profile_id'], ['uuid'])

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('experience_user_profile_id_fkey', 'user_profile', ['user_profile_id'], ['uuid'])

    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('education_user_profile_id_fkey', 'user_profile', ['user_profile_id'], ['uuid'])

    # ### end Alembic commands ###
