"""empty message

Revision ID: f1aac4333d08
Revises: 29b341950ba0
Create Date: 2023-09-20 12:42:13.387014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1aac4333d08'
down_revision = '29b341950ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certifications', sa.Text(), nullable=True))
        batch_op.drop_constraint('user_profile_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_profile_email_key', ['email'])
        batch_op.drop_column('certifications')

    # ### end Alembic commands ###
